export const typeValue = {
    LOGIN: 'LOGIN',
    CREATE_TASK: 'CREATE_TASK',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CREATE_USER: 'CREATE_USER',
    CREATE_USER: 'CREATE_USER',
    DEAD_LINE: 'DEAD_LINE',
}

export const DATETIME_FORMAT_DISPLAY = "HH:mm DD/MM/YYYY";
